Mxonline3/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
# 导入xadmin，替换admin
from django.views.static import serve

import xadmin
from django.conf import settings
from django.conf.urls.static import static

from users.views import LoginView, RegisterView, ActiveUserView, ForgetPwdView,\
    ResetView, ModifyPwdView, LogoutView, IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('xadmin/', xadmin.site.urls),  # x_admin
    path('captcha/', include('captcha.urls')),  # 验证码
    path('ueditor/', include('DjangoUeditor.urls')),  # 富文本

    path('', IndexView.as_view(), name='index'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    # 注册
    path('register/', RegisterView.as_view(), name='register'),
    # 激活用户
    re_path(r'active/(?P<active_code>.*)/', ActiveUserView.as_view(), name='user_active'),
    # 忘记密码
    path('forget/', ForgetPwdView.as_view(), name='forget_pwd'),
    # 重置密码url：用来接收来自邮箱的重置链接
    re_path(r'reset/(?P<active_code>.*)/', ResetView.as_view(), name='reset_pwd'),
    # 修改密码, 只接收post请求
    path('modify_pwd/', ModifyPwdView.as_view(), name='modify_pwd'),

    # organization app, teacher
    path('org/', include('organization.urls', namespace='org')),
    # course
    path('course/', include('courses.urls', namespace='course')),
    # user
    path('users/', include('users.urls', namespace='users')),

]

# 处理图片显示的url,使用Django自带serve,传入参数路径
# 开发阶段配置配置上传文件
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/courses/urls.py
from courses.views import CourseListView, CourseDetailView, CourseInfoView,\
    CommentsView, AddCommentsView, VideoPlayView
from django.urls import path, re_path

app_name = 'courses'
urlpatterns = [
    # 课程列表url
    path('list/', CourseListView.as_view(), name='list'),
    # 课程详情
    re_path('detail/(?P<course_id>\d+)/', CourseDetailView.as_view(), name='course_detail'),
    # 课程章节列表
    re_path('info/(?P<course_id>\d+)/', CourseInfoView.as_view(), name='course_info'),
    # 课程评论
    re_path('comments/(?P<course_id>\d+)/', CommentsView.as_view(), name='course_comments'),
    # 添加课程评论
    path('add_comment/', AddCommentsView.as_view(), name='add_comment'),
    # 课程视频播放页
    re_path('video/(?P<video_id>\d+)/', VideoPlayView.as_view(), name='video_play'),
]

apps/organization/urls.py
from organization.views import OrgView, AddUserAskView, OrgHomeView, OrgCourseView, \
    OrgDescView, OrgTeacherView, AddFavView, TeacherListView, TeacherDetailView

from django.urls import path, re_path

app_name = 'organization'
urlpatterns = [
    # 课程机构列表
    path('list/', OrgView.as_view(), name='org_list'),
    # 机构首页
    re_path('home/(?P<org_id>\d+)/', OrgHomeView.as_view(), name='org_home'),
    # 访问课程
    re_path('course/(?P<org_id>\d+)/', OrgCourseView.as_view(), name='org_course'),
    # 机构描述
    re_path('desc/(?P<org_id>\d+)/', OrgDescView.as_view(), name='org_desc'),
    # 机构讲师
    re_path('org_teacher/(?P<org_id>\d+)/', OrgTeacherView.as_view(), name='org_teacher'),
    # 用户咨询，post，在机构列表页
    path('add_ask/', AddUserAskView.as_view(), name='add_ask'),
    # 机构收藏， post
    path('add_fav/', AddFavView.as_view(), name='add_fav'),

    # 讲师列表
    path('teacher/list/', TeacherListView.as_view(), name='teacher_list'),
    # 讲师详情
    re_path('teacher/detail/(?P<teacher_id>\d+)/', TeacherDetailView.as_view(), name='teacher_detail'),
]

apps/users/urls.py
from django.urls import path

from users.views import UserInfoView, UploadImageView, SendEmailCodeView, \
    UpdateEmailView, UpdatePwdView, MyCourseView, MyFavOrgView, \
    MyFavTeacherView, MyFavCourseView, MyMessageView

app_name = 'users'
urlpatterns = [
    # 用户信息
    path('info/', UserInfoView.as_view(), name='user_info'),
    # 用户头像上传
    path('image/upload/', UploadImageView.as_view(), name='image_upload'),
    # 用户个人中心修改密码
    path('update/pwd/', UpdatePwdView.as_view(), name='update_pwd'),
    # 专用于发送验证码的
    path('sendemail_code/', SendEmailCodeView.as_view(), name='sendemail_code'),
    # 修改邮箱
    path('update_email/', UpdateEmailView.as_view(), name='update_email'),
    # 我的课程
    path('mycourse/', MyCourseView.as_view(), name='mycourse'),
    # 我收藏的课程机构
    path('myfav/org/', MyFavOrgView.as_view(), name='myfav_org'),
    # 我收藏的授课讲师
    path('myfav/teacher/', MyFavTeacherView.as_view(), name='myfav_teacher'),
    # 我收藏的课程
    path('myfav/course/', MyFavCourseView.as_view(), name='myfav_course'),
    # 我的消息
    path('my_message/', MyMessageView.as_view(), name='my_message'),
]

extra_apps/DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

apps/courses/models.py
from datetime import datetime
from django.db import models
from django.utils import timezone

from DjangoUeditor.models import UEditorField
from organization.models import CourseOrg, Teacher


class Course(models.Model):
    """课程信息表"""
    DEGREE_CHOICES = (
        ('cj', '初级'),
        ('zj', '中级'),
        ('gj', '高级')
    )
    course_org = models.ForeignKey(CourseOrg, on_delete=models.CASCADE, verbose_name='所属机构', null=True, blank=True)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, verbose_name='讲师', null=True, blank=True)
    name = models.CharField('课程名', max_length=50)
    desc = models.CharField('课程描述', max_length=300)
    # 修改imagepath,不能传y m 进来，不能加斜杠是一个相对路径，相对于setting中配置的mediaroot
    detail = UEditorField('课程详情', width=600, height=300, imagePath='courses/ueditor/', filePath='courses/ueditor/', default='')
    is_banner = models.BooleanField('是否轮播', default=False)
    degree = models.CharField('难度', choices=DEGREE_CHOICES, max_length=2)
    learn_times = models.IntegerField('学习时长(分钟数)', default=0)
    students = models.IntegerField('学习人数', default=0)
    fav_nums = models.IntegerField('收藏人数', default=0)
    you_need_know = models.CharField('课程须知', max_length=300, default='一颗勤学的心是本课程必要前提')
    teacher_tell = models.CharField('老师告诉你', max_length=300, default='什么都可以学到,按时交作业,不然叫家长')
    image = models.ImageField('封面图', upload_to='courses/%Y/%m',  max_length=100)
    click_nums = models.IntegerField('点击数', default=0)
    category = models.CharField('课程类别', max_length=20, default='后端开发')
    tag = models.CharField('课程标签', max_length=15, default='')
    add_time = models.DateTimeField('添加时间', default=datetime.now)

    class Meta:
        db_table = 'course'
        verbose_name = '课程'
        verbose_name_plural = verbose_name


    def __str__(self):
        return self.name


class Lesson(models.Model):
    """章节"""
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name='课程')
    name = models.CharField('章节名', max_length=100)
    add_time = models.DateTimeField('添加时间', default=datetime.now)

    class Meta:
        db_table = 'lesson'
        verbose_name = '章节'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '《{0}》课程的章节 >> {1}'.format(self.course, self.name)


class Video(models.Model):
    """每章视频"""
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, verbose_name='章节')
    url = models.CharField('访问地址', max_length=200, default='')
    name = models.CharField('视频名', max_length=100)
    learn_times = models.IntegerField('学习时长(分钟数)', default=0)
    add_time = models.DateTimeField('添加时间', default=datetime.now)

    class Meta:
        db_table = 'video'
        verbose_name = '视频'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '{0}的视频 >> {1}'.format(self.lesson, self.name)


class CourseResource(models.Model):
    """课程资源"""
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name='课程')
    name = models.CharField('名称', max_length=100)
    # FileField是一个字符串类型，要指定最大长度。
    download = models.FileField('资源文件', upload_to='course/resource/%Y/%m', max_length=100)
    add_time = models.DateTimeField('添加时间', default=datetime.now)

    class Meta:
        db_table = 'course_resource'
        verbose_name = '课程资源'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '《{0}》课程的资源: {1}'.format(self.course, self.name)

templates/base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
    <title>	{% block titile %}首页 | 微慕课{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% block custom_css %} {% endblock %}
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>
</head>
<body>
<section class="headerwrap ">
    <header>
        <div  class=" header">
            <div class="top">
                {% if request.user.is_authenticated %}
                    <div class="wp">
                        <div class="fl"><p>服务电话：<b>23333333</b></p></div>
                        <div class="personal">
                            <dl class="user fr">
                                <dd>{{ user.username }}<img class="down fr" src="{% static 'images/top_down.png' %}"/></dd>
                                <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ user.image }}"/></dt>
                            </dl>
                            <div class="userdetail">
                                <dl>
                                    <dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ user.image }}"/></dt>
                                    <dd>
                                        <h2>{{ user.nick_name }}</h2>
                                        <p>{{ user.username }}</p>
                                    </dd>
                                </dl>
                                <div class="btn">
                                    <a class="personcenter fl" href="{% url 'users:user_info' %}">进入个人中心</a>
                                    <a class="fr" href="{% url 'logout' %}">退出</a>
                                </div>
                            </div>
                        </div>
                        <a href="{% url 'users:my_message' %}">
                            <div class="msg-num"><span id="MsgNum">{{ request.user.unread_nums }}</span></div>
                        </a>
                    </div>
                {% else %}
                    <div class="wp">
                        <div class="fl"><p>服务电话：<b>23333333</b></p></div>
                        <!--登录后跳转-->
                        <a style="color:white" class="fr registerbtn" href="{% url "register" %}">注册</a>
                        <a style="color:white" class="fr loginbtn" href="{% url 'login'%}?next={{ request.path }}">登录</a>
                    </div>
                {% endif %}
            </div>

            <div class="middle">
                <div class="wp">
                    <a href="{% url 'index' %}"><img class="fl" src="{% static 'images/logo.jpg' %}"/></a>
                    <div class="searchbox fr">
                        <div class="selectContainer fl">
                            <span class="selectOption" id="jsSelectOption" {% ifequal  '/' request.path %}data-value="course"> 公开课{% endifequal %}{% ifequal  '/course' request.path|slice:":7" %}data-value="course"> 公开课 {% endifequal %}{% ifequal  '/org/teacher' request.path|slice:":12" %}data-value="teacher"> 授课教师{% endifequal %}{% ifequal  '/org/list' request.path|slice:":9" %}data-value="org"> 课程机构{% endifequal %}</span>
                            <ul class="selectMenu" id="jsSelectMenu">
                                <li data-value="course">公开课</li>
                                <li data-value="org">课程机构</li>
                                <li data-value="teacher">授课教师</li>
                            </ul>
                        </div>
                        <input id="search_keywords" class="fl" type="text" value="" placeholder="请输入搜索内容"/>
                        <img class="search_btn fr" id="jsSearchBtn" src="{% static 'images/search_btn.png' %}"/>
                    </div>
                </div>
            </div>
            <nav>
                <div class="nav">
                    <div class="wp">
                        <ul>
                            <li {% ifequal  '/' request.path %}
                                class="active"
                            {% endifequal %}><a href="{% url 'index' %}">首页</a></li>
                            <li  {% ifequal  '/course' request.path|slice:":7" %}
                                class="active"
                            {% endifequal %}>
                                <a href="{% url 'course:list' %}">
                                    公开课<img class="hot" src="{% static 'images/nav_hot.png' %}">
                                </a>
                            </li>
                            <li {% ifequal  '/org/teacher' request.path|slice:":12" %}
                                class="active"
                            {% endifequal %}>
                                <a href="{% url 'org:teacher_list' %}">授课教师</a>
                            </li>
                            <li {% ifequal  '/org/list' request.path|slice:":9" %}
                                class="active"
                            {% endifequal %}><a href="{% url 'org:org_list' %}">课程机构</a></li>
                        </ul>
                    </div>
                </div>
            </nav>

        </div>
    </header>
</section>
<!--crumbs start-->
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block content %}
{% endblock %}

<footer>
    <div class="footer">
        <div class="wp">
            <ul class="cont">
                <li class="logo"><a href="{% url 'index' %}"><img src="{% static 'images/footlogo.png' %}"/></a></li>
                <li class="code"><img src="{% static 'images/code.jpg' %}"/><p class="center">扫描关注微信</p></li>
                <li class="third"><img class="fl" src="{% static 'images/tell.png' %}"/><p class="tell">23333333</p><p class="time">周一至周日 9:00-18:00</p></li>
            </ul>
        </div>
        <p class="line"></p>
        <div class="wp clear">
            <span class="fl">©2019 微慕课-在线学习交流平台 保留所有权利</span>
            <span class="fr">copyright© 2019 ICP备案证书号：<a style="color:#717171 " href="http://www.miitbeian.gov.cn/">京ICP备xxxxxxxx号</a></span>
        </div>
    </div>
</footer>

<section>
    <ul class="sidebar">
{#        <li class="qq">#}
{#            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=1159977879&site=qq&menu=yes"></a>#}
{#        </li>#}
        <li class="totop"></li>
    </ul>
</section>

<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script src="{% static 'js/deco-common.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static '' %}js/plugins/laydate/laydate.js"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}"  type="text/javascript"></script>
<script src="{% static 'js/deco-common.js' %}"  type="text/javascript"></script>
{% block custom_js %} {% endblock %}
</body>
</html>

templates/org_base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
    <title>    {% block title %} 机构首页 | 微慕课{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">
    {% block custom_css %} {% endblock %}
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>
    {% block custom_js %} {% endblock %}
</head>
<body>
<section class="headerwrap headerwrap2">
    <header>
        <div  class="header2 header">
            <div class="top">
                {% if request.user.is_authenticated %}
                    <div class="wp">
                        <div class="fl"><p>服务电话：<b>23333333</b></p></div>
                        <div class="personal">
                            <dl class="user fr">
                                <dd>{{ user.username }}<img class="down fr" src="{% static 'images/top_down.png' %}"/></dd>
                                <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ user.image }}"/></dt>
                            </dl>
                            <div class="userdetail">
                                <dl>
                                    <dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ user.image }}"/></dt>
                                    <dd>
                                        <h2>{{ user.nick_name }}</h2>
                                        <p>{{ user.username }}</p>
                                    </dd>
                                </dl>
                                <div class="btn">
                                    <a class="personcenter fl" href="{% url 'users:user_info' %}">进入个人中心</a>
                                    <a class="fr" href="{% url 'logout' %}">退出</a>
                                </div>
                            </div>
                        </div>
                        <a href="{% url 'users:my_message' %}">
                            <div class="msg-num"><span id="MsgNum">{{ request.user.unread_nums }}</span></div>
                        </a>
                    </div>
                {% else %}
                    <div class="wp">
                        <div class="fl"><p>服务电话：<b>23333333</b></p></div>
                        <!--登录后跳转-->
                        <a style="color:white" class="fr registerbtn" href="{% url "register" %}">注册</a>
                        <a style="color:white" class="fr loginbtn" href="{% url 'login'%}?next={{ request.path }}">登录</a>
                    </div>
                {% endif %}
                <div class="middle companyheader">
                    <div class="wp">
                        <img class="fl" style="width: 112px;height: 103px" src="{{ MEDIA_URL }}{{ course_org.image }}"/>
                        <div class="head fl">
                            <h1>
                                {{ course_org.name }}
                                <img src="{% static 'images/authentication.png' %}"/>
                                <img src="{% static 'images/gold.png' %}"/>
                            </h1>
                            <p class="fl">
                                <span class="fl" style="margin-top:8px;color:#848484;">推荐指数： </span>
                                <span class="precision company-credit" data-star-scope="5.0"></span>
                                <span class="key">5.0</span>
                            </p>
                        </div>
                        <div class="btn fr collectionbtn  notlogin
                 "data-favid="22" data-fav-type="1">
                            {% if has_fav %}
                                已收藏
                            {% else %}
                                收藏
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
    </header>
</section>
<section>
    <div class="wp">
        <ul  class="crumbs">
            <li><a href="{% url 'index' %}">首页</a>></li>
            <li><a href="{% url 'org:org_list' %}">课程机构</a>></li>
            <li>{% block page_path %}机构首页{% endblock %}</li>
        </ul>
    </div>
</section>

<section>
    <div class="wp list personal_list comp">
        <div class="left">
            <ul>
                <li class="{% ifequal current_page "home" %}active2{% endifequal %}"><a href="{% url 'org:org_home' course_org.id %}">机构首页</a></li>
                <li class="{% ifequal current_page "course" %}active2{% endifequal %}"><a href="{% url 'org:org_course' course_org.id %}">机构课程</a></li>
                <li class="{% ifequal current_page "desc" %}active2{% endifequal %}"><a href="{% url 'org:org_desc' course_org.id %}">机构介绍</a></li>
                <li class="{% ifequal current_page "teacher" %}active2{% endifequal %}"><a href="{% url 'org:org_teacher' course_org.id %}">机构讲师</a></li>
            </ul>
        </div>
        {% block right_form %}
        {% endblock %}

</section>
<!--sidebar start-->
<section>
    <ul class="sidebar">
{#        <li class="qq">#}
{#            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>#}
{#        </li>#}
        <li class="totop"></li>
    </ul>
</section>
<!--sidebar end-->
<!--header start-->
</div>
<!--弹出省省市-->
<script src="/static/js/plugins/jquery.scrollLoading.js"  type="text/javascript"></script>
<script src="/static/js/deco-common.js" type='text/javascript'></script>
<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static '' %}js/plugins/laydate/laydate.js"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
<script type="text/javascript" src="{% static 'js/plugins/jquery.raty.js' %}"></script>
<script type="text/javascript">
    //收藏分享
    //收藏分享
    function add_fav(current_elem, fav_id, fav_type){
        $.ajax({
            cache: false,
            type: "POST",
            url:"{% url "org:add_fav" %}",
            data:{'fav_id':fav_id, 'fav_type':fav_type},
            async: true,
            beforeSend:function(xhr, settings){
                xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
            },
            success: function(data) {
                if(data.status == 'fail'){
                    if(data.msg == '用户未登录'){
                        window.location.href="{% url 'login' %}?next={{ request.path }}";
                    }else{
                        alert(data.msg)
                    }

                }else if(data.status == 'success'){
                    current_elem.text(data.msg)
                }
            },
        });
    }

    $('.collectionbtn').on('click', function(){
        add_fav($(this),{{ course_org.id }}, 2);
    });

    $(function(){
        var $precision = $('.precision'),
            score = $precision.attr('data-star-scope'),
            option =  {
                half		: true,
                path		: '{% static 'images/' %}',
                precision	: true,
                size		: 24,
                starOff		: 'g_star.png',
                starOn		: 'r_star.png',
                starHalf	: 'h_star.png',
                hints       : ['极差', '差', '一般', '好评', '非常满意'],
                noRatedMsg  : '暂时还未获得评价！',
                readOnly    : true,
                score       : score
            };
        $precision.raty(option);

        $('.jsFavBtn').on('click', function(){
            var type = $(this).attr('data-fav-type');
            if(type == '1'){
                favPraise($(this), 'fav' ,1 , '收藏');

            }else if(type == '3'){
                favPraise($(this), 'fav' ,3 );

            }else if(type == '11'){
                favPraise($(this), 'pra', 1);

            }else if(type == '4'){
                favPraise($(this), 'fav' ,4 );

            }
        });
    })
</script>


<script type="text/javascript">
    $(function() {
        $('.recordbtn1').click(function(){
            $('.recordbox1').show();
        });
        $('.recordbtn2').click(function(){
            $('.recordbox2').show();
        });

        $('.imgslide').unslider({
            speed: 500,               //  The speed to animate each slide (in milliseconds)
            delay: 3000,              //  The delay between slide animations (in milliseconds)
            complete: function() {},  //  A function that gets called after every slide animation
            keys: true,               //  Enable keyboard (left, right) arrow shortcuts
            dots: true,               //  Display dot navigation
            fluid: false              //  Support responsive design. May break non-responsive designs
        });
        var unslider = $('.imgslide').unslider();
        $('.unslider-arrow').click(function() {
            var fn = this.className.split(' ')[1];
            unslider.data('unslider')[fn]();
        });
    });
</script>

</body>
</html>

templates/usercenter-fav-course.html
{% extends 'usercenter-base.html' %}
{% block title %} 我的收藏 | 微慕课{% endblock %}
{% load staticfiles %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>

{% endblock %}
{% block right_content %}

    <div class="right" >
        <div class="personal_des Releasecont">
            <div class="head">
                <h1>我的收藏</h1>
            </div>
        </div>
        <div class="personal_des permessage">
            <div class="head">
                <ul class="tab_header messagehead">
                    <li ><a href="{% url 'users:myfav_org' %}">课程机构</a> </li>
                    <li><a href="{% url 'users:myfav_teacher' %}">授课教师 </a></li>
                    <li class="active"><a href="{% url 'users:myfav_course' %}">公开课程</a></li>
                </ul>
            </div>
            <div class="companycenter">
                <div class="group_list brief">
                    {% for course in course_list %}
                        <div class="module1_5 box">
                            <a href="{% url 'course:course_detail' course.id %}">
                                <img width="214" height="190" src="{{ MEDIA_URL }}{{  course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="{% url 'course:course_detail' course.id %}"><h2>{{ course.name }}</h2></a>
                                <span class="fl">时长：<i class="key">{{ coure.learn_times }}</i></span>
                                <span class="fr">学习人数：{{ course.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ course.course_org.name }}</span>
                                <span class="delete-group fr jsDeleteFav_course" data-favid="{{ course.id }}"></span>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/usercenter-fav-org.html
{% extends 'usercenter-base.html' %}
{% block title %} 我的收藏 | 微慕课{% endblock %}
{% load staticfiles %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block right_content %}
    <div class="right" >
        <div class="personal_des Releasecont">
            <div class="head">
                <h1>我的收藏</h1>
            </div>
        </div>
        <div class="personal_des permessage">
            <div class="head">
                <ul class="tab_header messagehead">
                    <li class="active"><a href="{% url 'users:myfav_org' %}">课程机构</a> </li>
                    <li><a href="{% url 'users:myfav_teacher' %}">授课教师 </a></li>
                    <li><a href="{% url 'users:myfav_course' %}">公开课程</a></li>
                </ul>
            </div>
            <div class="messagelist">
                {% for org in org_list  %}
                    <div class="messages butler_list company company-fav-box">
                        <dl class="des fr">
                            <dt>
                                <a href="{% url 'org:org_home' org.id %}">
                                    <img width="160" height="90" src="{{ MEDIA_URL }}{{ org.image }}"/>
                                </a>
                            </dt>
                            <dd>
                                <h1><a href="{% url 'org:org_home' org.id %}">{{ org.name }}</a></h1>
                                <div class="pic fl" style="width:auto;">
                                    <img src="{% static 'images/authentication.png' %}"/>
                                    <img src="{% static 'images/gold.png' %}"/>
                                </div>
                                <span class="c8 clear">{{ org.city.name }}</span>
                                <div class="delete jsDeleteFav_org" data-favid="{{ org.id }}"></div>
                            </dd>
                        </dl>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}